name: smart_memory_app
description: تطبيق ذاكرتي الذكية المحلي
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  fl_chart: ^0.66.0
  share_plus: ^10.1.0 # تم إضافة مكتبة المشاركة

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/IconMain.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
